import AnnotatorExample from "./integrated/AnnotatorExample"
import DiagramExample from "./integrated/DiagramExample"
import MotionStudioExample from "./integrated/MotionStudioExample"
import ChildrenExample from "./simple/ChildrenExample"
import EventsExample from "./simple/EventsExample"
import HistoryExample from "./simple/HistoryExample"
import LayersExample from "./simple/LayersExample"
import SelectorsExample from "./simple/SelectorsExample"
import ShapesExample from "./simple/ShapesExample"
import StateExample from "./simple/StateExample"
import TimelineExample from "./simple/TimelineExample"
import TransferExample from "./simple/TransferExample"
import TransformExample from "./simple/TransformExample"
import { ExampleDefinition } from "./types"

export const catalog: ExampleDefinition[] = [
  {
    path: "/simple/shapes",
    sourcePath: "./examples/simple/ShapesExample.tsx",
    group: "Simple",
    order: 1,
    title: "Shapes and drawing styles",
    shortTitle: "Shapes",
    summary: "Render the stable built-in primitives with fill, stroke, dash, opacity, text, and a raster image.",
    features: ["Rectangle", "Circle", "Line", "StayText", "StayImage"],
    instructions: ["Confirm all five shape families are visible.", "Toggle the rectangle twice.", "Force a refresh after the canvas becomes idle."],
    checklist: ["Fill and stroke colors remain distinct.", "The dashed line retains round caps.", "The image and text stay sharp at device pixel ratio.", "Updating one Shape repaints without recreating the Canvas."],
    component: ShapesExample,
  },
  {
    path: "/simple/children",
    sourcePath: "./examples/simple/ChildrenExample.tsx",
    group: "Simple",
    order: 2,
    title: "Child lifecycle",
    shortTitle: "Children",
    summary: "Create, mutate, query, and remove Children, including a Child that owns multiple Shapes.",
    features: ["appendChild", "shapeMap", "update", "removeChild", "hasChild"],
    instructions: ["Append three circular Children.", "Move the multi-shape group.", "Remove the most recent circle."],
    checklist: ["The Child count follows each operation.", "Rectangle and text move together.", "Removing a Child clears its previous pixels.", "The multi-shape Child reports two Shapes."],
    component: ChildrenExample,
  },
  {
    path: "/simple/layers",
    sourcePath: "./examples/simple/LayersExample.tsx",
    group: "Simple",
    order: 3,
    title: "Layers and paint order",
    shortTitle: "Layers",
    summary: "Route Shapes across three Canvas layers and reorder overlapping Shapes with zIndex.",
    features: ["layers", "Shape.layer", "zIndex", "dirty layers"],
    instructions: ["Observe the initial orange-over-blue stack.", "Swap zIndex repeatedly.", "Confirm the text overlay never moves behind the stack."],
    checklist: ["Only the two Shapes on layer 1 exchange order.", "Layer 2 remains above layers 0 and 1.", "No cleared pixels leak between Canvas layers."],
    component: LayersExample,
  },
  {
    path: "/simple/events",
    sourcePath: "./examples/simple/EventsExample.tsx",
    group: "Simple",
    order: 4,
    title: "Events and listeners",
    shortTitle: "Events",
    summary: "Exercise predefined pointer and key events, drag composeStore, focus, and programmatic custom actions.",
    features: ["listenerList", "drag chain", "composeStore", "ref.trigger", "payload"],
    instructions: ["Drag the blue rectangle, then capture the drag entries before continuing.", "Focus the Canvas and press a key.", "Scroll over the Canvas.", "Trigger the custom ping from React."],
    checklist: ["The log contains dragstart, drag, and dragend in emission order, displayed newest first.", "The target follows the pointer without jumping.", "Keyboard and wheel events reach listeners.", "The custom payload is visible in the log."],
    component: EventsExample,
  },
  {
    path: "/simple/selectors",
    sourcePath: "./examples/simple/SelectorsExample.tsx",
    group: "Simple",
    order: 5,
    title: "Selectors and hit testing",
    shortTitle: "Selectors",
    summary: "Query Children by class, id, logical expression, and pointer containment.",
    features: [".class", "#id", "& | !", "getContainPointChildren"],
    instructions: ["Run every preset selector.", "Enter .label|#box-b and run the query.", "Click each visible rectangle and the empty area."],
    checklist: ["Orange outlines match the reported ids.", "Logical NOT excludes box-a.", "The custom query matches box-b and label-a.", "Pointer hits report the clicked Child.", "Clicking empty space does not report a Shape."],
    component: SelectorsExample,
  },
  {
    path: "/simple/state",
    sourcePath: "./examples/simple/StateExample.tsx",
    group: "Simple",
    order: 6,
    title: "State and stores",
    shortTitle: "State",
    summary: "Gate listeners by stage state while comparing persistent store with state-scoped store.",
    features: ["switchState", "Listener.state", "store", "stateStore"],
    instructions: ["Create two circles in Draw mode.", "Switch to Select and highlight one circle.", "Switch modes again and click the Canvas."],
    checklist: ["Draw listeners do not fire in Select mode.", "Select listeners only target existing circles.", "Persistent store keeps increasing.", "State store resets after every state change."],
    component: StateExample,
  },
  {
    path: "/simple/history",
    sourcePath: "./examples/simple/HistoryExample.tsx",
    group: "Simple",
    order: 7,
    title: "Undo and redo history",
    shortTitle: "History",
    summary: "Log deterministic append and remove operations, then travel backward and forward through snapshots.",
    features: ["log", "undo", "redo", "snapshot"],
    instructions: ["Add and log three rectangles.", "Undo to an empty Canvas, then press Undo once more and confirm the count stays at zero.", "Redo all three operations, then press Redo once more and confirm the count stays at three.", "Remove the last rectangle and undo the removal.", "Add and log one rectangle, then press Redo and confirm the count does not change."],
    checklist: ["Each effective history operation changes the visible count once.", "Undo stops safely at the beginning.", "Redo stops safely at the end.", "A new logged operation truncates the old redo tail."],
    component: HistoryExample,
  },
  {
    path: "/simple/transform",
    sourcePath: "./examples/simple/TransformExample.tsx",
    group: "Simple",
    order: 8,
    title: "Pan and zoom transforms",
    shortTitle: "Transform",
    summary: "Move and scale the scene from controls or native wheel and Control-drag gestures.",
    features: ["moveStart", "move", "zoom", "reset"],
    instructions: ["Pan with the toolbar.", "Zoom around the center with the toolbar.", "Use the mouse wheel at two different points.", "Control-drag the scene and reset."],
    checklist: ["Every Child keeps its relative position.", "Pointer-centered zoom uses the pointer as origin.", "Control-drag does not trigger normal drawing.", "Reset restores the initial framing."],
    component: TransformExample,
  },
  {
    path: "/simple/timeline",
    sourcePath: "./examples/simple/TimelineExample.tsx",
    group: "Simple",
    order: 9,
    title: "Keyframe timeline",
    shortTitle: "Timeline",
    summary: "Seek and play multiple animated Children with delay and easing on one explicit clock.",
    features: ["createChild", "appendKeyFrame", "progress", "easing", "delay"],
    instructions: ["Drag the time slider slowly through every segment.", "Play from the beginning.", "Jump directly to the end and back to zero."],
    checklist: ["The zero frame is transparent.", "Geometry and color interpolate between keys.", "The delay window holds the previous frame.", "Exact end time lands on the final frame."],
    component: TimelineExample,
  },
  {
    path: "/simple/transfer",
    sourcePath: "./examples/simple/TransferExample.tsx",
    group: "Simple",
    order: 10,
    title: "Import, export, and capture",
    shortTitle: "Transfer",
    summary: "Copy a scene between stages and render Children into a standalone target Canvas.",
    features: ["exportChildren", "importChildren", "regionToTargetCanvas"],
    instructions: ["Transfer the scene once.", "Move the source asset and confirm the target copy stays put.", "Move the target copy and confirm the source stays put.", "Transfer again, then capture the source region."],
    checklist: ["Target geometry matches the source.", "Repeated import creates additional Children.", "The captured bitmap contains all source Shapes.", "Source and target remain independently mutable."],
    component: TransferExample,
  },
  {
    path: "/integrations/annotator",
    sourcePath: "./examples/integrated/AnnotatorExample.tsx",
    group: "Integrated",
    order: 11,
    title: "Image annotation workspace",
    shortTitle: "Annotator",
    summary: "A complete draw, select, move, delete, undo, zoom, and export workflow over a raster image.",
    features: ["StayImage", "layers", "state", "drag", "history", "capture"],
    instructions: ["Draw two annotations.", "Select and move one annotation.", "Delete it, then undo and redo.", "Zoom the scene, reset the view, and export."],
    checklist: ["Annotations remain above the image layer.", "Mode switching changes listener behavior and cursor.", "Creation and deletion participate in history.", "Selection uses hit testing.", "The exported bitmap includes image and annotations."],
    component: AnnotatorExample,
  },
  {
    path: "/integrations/diagram",
    sourcePath: "./examples/integrated/DiagramExample.tsx",
    group: "Integrated",
    order: 12,
    title: "Connected diagram editor",
    shortTitle: "Diagram",
    summary: "Multi-shape nodes, dependent edges, state-driven connection mode, transforms, and scene transfer.",
    features: ["multi-shape Child", "Line", "stateStore", "drag", "import/export"],
    instructions: ["Drag each initial node and observe its edges.", "Connect two nodes in Connect mode.", "Add a node and zoom the diagram.", "Save the scene and import a copy.", "Drag an offset imported node from its exposed edge and observe the copied edges."],
    checklist: ["Node labels move with their rectangles.", "Edges follow both endpoints.", "Connection state clears after the second node.", "Canvas layers keep edges behind nodes.", "Imported Children are offset copies whose edges move independently from the originals."],
    component: DiagramExample,
  },
  {
    path: "/integrations/motion-studio",
    sourcePath: "./examples/integrated/MotionStudioExample.tsx",
    group: "Integrated",
    order: 13,
    title: "Motion composition studio",
    shortTitle: "Motion studio",
    summary: "Coordinate shape, line, and text tracks while static Children retain normal history semantics.",
    features: ["multiple tracks", "progress bound", "layers", "static history"],
    instructions: ["Play and scrub the full timeline.", "Switch to the bounded middle range and scrub again.", "Add two static guides and undo them."],
    checklist: ["All animated tracks share one time value.", "Bound playback remaps the selected sub-range.", "Static guides can be undone.", "Undo never removes or freezes timeline Children.", "Layer ordering stays stable while seeking."],
    component: MotionStudioExample,
  },
]

export function getExampleByPath(path: string) {
  return catalog.find((example) => example.path === path)
}
